# See: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
version: 2.1

jobs:
  docs-build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Setup Python environment
          command: |
            python3 -m venv /home/circleci/usb2ttl_env
            echo "source /home/circleci/usb2ttl_env/bin/activate" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            python -m pip install -U pip
            python -m pip install -r requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html
      - store_artifacts:
          path: docs/_build/html
          destination: html

  docs-deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          # do not update gh-pages above 3.0.0
          # see: https://github.com/tschaub/gh-pages/issues/354
          command: |
            npm install -g --silent gh-pages@3.0.0
            git config user.email "CircleCI@bot.com"
            git config user.name "CircleCI"
      - add_ssh_keys:
          fingerprints:
            - "89:63:62:01:d6:a2:9e:da:b0:c1:d3:e0:f5:30:72:e1"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "doc updates [skip ci]" --dist docs/_build/html

workflows:
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master

    triggers:
      - schedule:
          cron: "0 4 1 * *"
          filters:
            branches:
              only:
                - master
